// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxedmfrqxbgznmcvagon.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4ZWRtZnJxeGJnem5tY3ZhZ29uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4NzM4MzMsImV4cCI6MjA2NzQ0OTgzM30.vcOgoyCmzYTEdPTrernlB6WoDtyJQpuqFDrxHp2NHXk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});